server:
  port: 4002
spring:
  datasource:
    url: jdbc:mysql://139.199.17.156:3306/lostandfound
    username: lost
    password: lostandfound
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false



  jpa:
      properties:
        hibernate:
          hbm2ddl:
            auto: update
